version: '3'
services:
  
  docker-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    image: docker-nginx
    container_name: docker-nginx
    hostname: docker-apache
    networks:
      - reverseproxy
  
  docker-apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    #image: httpd:alpine
    restart: always
    image: docker-apache
    container_name: docker-apache
    hostname: docker-apache
    networks:
      - reverseproxy
  
  docker-reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
    image: docker-reverseproxy
    container_name: docker-reverseproxy
    hostname: docker-reverseproxy 
    networks:
      - reverseproxy
  
networks:
  reverseproxy:
