version: '3'
services:
  reverseproxy:
#   image: reverseproxy
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
 
  nginx:
    depends_on:
      - reverseproxy
    #image: nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
 
  apache:
    depends_on:
      - reverseproxy
    build:
      context: ./apache
      dockerfile: Dockerfile
    #image: httpd:alpine
    restart: always
